/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/client-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client Msg */
        post: operations["client_msg_client_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Server Msg */
        post: operations["server_msg_server_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payloads/send-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** P1 */
        post: operations["p1_payloads_send_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckDeleteMultipleMessagesItem */
        AckDeleteMultipleMessagesItem: {
            /** Id */
            id: string;
            /**
             * Deletetype
             * @enum {string}
             */
            deleteType: "deleteForMe" | "deleteForEveryone" | "both";
            /** Deletedforeveryoneat */
            deletedForEveryoneAt?: string | null;
            /** Deletedformeat */
            deletedForMeAt?: string | null;
            /** Error */
            error?: string | null;
        };
        /** AckDeleteMultipleMessagesPayload */
        AckDeleteMultipleMessagesPayload: {
            /**
             * Protocolversion
             * @default 1.0
             */
            protocolVersion: string;
            /** Messages */
            messages: components["schemas"]["AckDeleteMultipleMessagesItem"][];
        };
        /** AckEditMessagePayload */
        AckEditMessagePayload: {
            /** Id */
            id: string;
            /** Editedat */
            editedAt: string;
        };
        /** AckSendMessagePayload */
        AckSendMessagePayload: {
            /** Id */
            id: string;
            /** Servertimestamp */
            serverTimestamp: string;
        };
        /** DeleteMultipleMessagesItem */
        DeleteMultipleMessagesItem: {
            /** Id */
            id: number | string;
            /**
             * Deletetype
             * @enum {string}
             */
            deleteType: "deleteForMe" | "deleteForEveryone" | "both";
            /** Deletedforeveryoneat */
            deletedForEveryoneAt?: number | string | null;
            /** Deletedformeat */
            deletedForMeAt?: number | string | null;
        };
        /** DeleteMultipleMessagesPayload */
        DeleteMultipleMessagesPayload: {
            /**
             * Protocolversion
             * @default 1.0
             */
            protocolVersion: string;
            /** Messages */
            messages: components["schemas"]["DeleteMultipleMessagesItem"][];
        };
        /** EditMessagePayload */
        EditMessagePayload: {
            /** Id */
            id: number | string;
            /** Text */
            text: string;
            /** Editedat */
            editedAt?: number | string | null;
        };
        /** ErrorPayload */
        ErrorPayload: {
            /** Message */
            message: string;
        };
        /** MessageStatusBroadcastPayload */
        MessageStatusBroadcastPayload: {
            /** Messageid */
            messageId: string;
            /** Status */
            status: string;
        };
        /** MessageStatusPayload */
        MessageStatusPayload: {
            /** Messageid */
            messageId: number | string;
            /**
             * Status
             * @enum {string}
             */
            status: "read" | "delivered";
        };
        /** OnlineUsersPayload */
        OnlineUsersPayload: {
            /** User Ids */
            user_ids: number[];
            /** Message */
            message: string;
        };
        /** PresenceBroadcastPayload */
        PresenceBroadcastPayload: {
            /** Userid */
            userId: string;
            /** Status */
            status: string;
        };
        /** PresencePayload */
        PresencePayload: {
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "offline";
        };
        /** ReceiveDeleteMultipleMessagesItem */
        ReceiveDeleteMultipleMessagesItem: {
            /** Id */
            id: string;
            /**
             * Deletetype
             * @enum {string}
             */
            deleteType: "deleteForEveryone" | "both";
            /** Deletedforeveryoneat */
            deletedForEveryoneAt: string;
        };
        /** ReceiveDeleteMultipleMessagesPayload */
        ReceiveDeleteMultipleMessagesPayload: {
            /**
             * Protocolversion
             * @default 1.0
             */
            protocolVersion: string;
            /** Messages */
            messages: components["schemas"]["ReceiveDeleteMultipleMessagesItem"][];
        };
        /** ReceiveEditMessagePayload */
        ReceiveEditMessagePayload: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Editedat */
            editedAt?: string | null;
            /**
             * Isedited
             * @default true
             */
            isEdited: boolean;
        };
        /** ReceiveMessagePayload */
        ReceiveMessagePayload: {
            /** Id */
            id: string;
            /** Chatid */
            chatId: string;
            /** Text */
            text: string;
            /** Senderid */
            senderId: string;
            /** Createdat */
            createdAt: string;
            /** Servertimestamp */
            serverTimestamp: string;
            /** Isdeletedforeveryone */
            isDeletedForEveryone: boolean;
            /**
             * Isedited
             * @default false
             */
            isEdited: boolean;
            /** Replyto */
            replyTo?: string | null;
        };
        /** SendMessagePayload */
        SendMessagePayload: {
            /** Chatid */
            chatId: number;
            /** Text */
            text: string;
            /** Id */
            id: number | string;
            /** Replyto */
            replyTo?: string | null;
            /** Createdat */
            createdAt?: number | string | null;
        };
        /** TypingBroadcastPayload */
        TypingBroadcastPayload: {
            /** Chatid */
            chatId: string;
            /** Userid */
            userId: string;
            /** Istyping */
            isTyping: boolean;
        };
        /** TypingPayload */
        TypingPayload: {
            /** Chatid */
            chatId: number;
            /** Istyping */
            isTyping: boolean;
        };
        /** WsClientMessage */
        WsClientMessage: {
            /**
             * Event
             * @enum {string}
             */
            event: "SEND_MSG" | "TYPING" | "MSG_STATUS" | "PRESENCE" | "EDIT_MSG" | "DELETE_MSGS";
            /** Payload */
            payload: components["schemas"]["SendMessagePayload"] | components["schemas"]["TypingPayload"] | components["schemas"]["MessageStatusPayload"] | components["schemas"]["PresencePayload"] | components["schemas"]["EditMessagePayload"] | components["schemas"]["DeleteMultipleMessagesPayload"];
            /** Timestamp */
            timestamp?: number | string | null;
        };
        /** WsServerMessage */
        WsServerMessage: {
            /**
             * Event
             * @enum {string}
             */
            event: "ACK_SEND_MSG" | "RECEIVE_MSG" | "TYPING" | "MSG_STATUS" | "PRESENCE" | "ACK_EDIT_MSG" | "RECEIVE_EDIT_MSG" | "ACK_DELETE_MSGS" | "RECEIVE_DELETE_MSGS" | "ERROR" | "ONLINE_USERS";
            /** Payload */
            payload: components["schemas"]["AckSendMessagePayload"] | components["schemas"]["ReceiveMessagePayload"] | components["schemas"]["TypingBroadcastPayload"] | components["schemas"]["MessageStatusBroadcastPayload"] | components["schemas"]["PresenceBroadcastPayload"] | components["schemas"]["AckEditMessagePayload"] | components["schemas"]["ReceiveEditMessagePayload"] | components["schemas"]["AckDeleteMultipleMessagesPayload"] | components["schemas"]["ReceiveDeleteMultipleMessagesPayload"] | components["schemas"]["ErrorPayload"] | components["schemas"]["OnlineUsersPayload"];
            /** Timestamp */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    client_msg_client_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsClientMessage"];
                };
            };
        };
    };
    server_msg_server_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsServerMessage"];
                };
            };
        };
    };
    p1_payloads_send_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessagePayload"];
                };
            };
        };
    };
}
